### ISSUE TITLE
1.8.0.6 prevents client from logging in

### ISSUE THREAD

**Issue by kreezxil** [Vorquel/Similsax-Transtructors#2]
The attached FML log indicateds NEI, but I took NEI out and still got the error. Then it indicated Tabby Chat 2, so I took that out and still got the error. So, put them back and took at the 1.8.0.6 version of Transtructors and bingo, no more errors.

Primary error:

```
[07:36:37] [Client thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
    at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1019) [bsu.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1025) ~[cee.class:?]
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27) ~[jh.class:?]
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10) ~[jh.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
    at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
    ... 17 more
```

FML Client Log: https://paste.ee/p/Rn8zs

Screen Shot
![image](https://cloud.githubusercontent.com/assets/3880072/9310649/ad070620-44d6-11e5-8020-2d65b7496dbd.png)

**Comment by Vorquel** [comment]
Bug confirmed. Trying to fix now.

**Comment by Vorquel** [comment]
Fix is out on curseforge
